const SHOW_SIGNUP = "SHOW_SIGNUP"
const HIDE_SIGNUP = "HIDE_SIGNUP"

const SHOW_SIGNIN = "SHOW_SIGNIN"
const HIDE_SIGNIN = "HIDE_SIGNIN"

const LOGIN_USER = "LOGIN_USER"
const LOGOUT = "LOGOUT"

const GAME_MODE = "GAME_MODE"

export {SHOW_SIGNUP, HIDE_SIGNUP, SHOW_SIGNIN, HIDE_SIGNIN, LOGIN_USER, LOGOUT, GAME_MODE};